### PR TITLE
Expose repositories as auto-wired services

### LINKED ISSUE #306: Fix deprecation in librecores.util.githubapiservice
```
The "librecores.util.githubapiservice" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.
```

### PR DESCRIPTION
**Pull request by agathver**
This allows us to mock repositories easily in tests.

Fixes #306, #310, #313

### CODE REVIEW

File: site/src/Librecores/ProjectRepoBundle/Controller/OrganizationController.php [hunk 1]
```diff
@@ -104,27 +112,32 @@ public function viewAction(Organization $organization)
         $user = $this->getUser();
 
         foreach ($organization->getMembers() as $m) {
-            if ($m->getPermission() === OrganizationMember::PERMISSION_REQUEST) {
+            if ($m->getPermission(
+                ) === OrganizationMember::PERMISSION_REQUEST) {
```
Comment (imphil) [inline site/src/Librecores/ProjectRepoBundle/Controller/OrganizationController.php]: That formatting is awful.

File: site/src/Librecores/ProjectRepoBundle/Controller/OrganizationController.php [hunk 2]
```diff
@@ -461,8 +507,10 @@ private function userIsMember(Organization $organization)
     {
         foreach ($organization->getMembers() as $m) {
             if (($m->getUser() === $this->getUser()) &&
-                ($m->getPermission() === OrganizationMember::PERMISSION_MEMBER ||
-                    $m->getPermission() === OrganizationMember::PERMISSION_ADMIN)) {
+                ($m->getPermission(
+                    ) === OrganizationMember::PERMISSION_MEMBER ||
+                    $m->getPermission(
+                    ) === OrganizationMember::PERMISSION_ADMIN)) {
```
Comment (imphil) [inline site/src/Librecores/ProjectRepoBundle/Controller/OrganizationController.php]: no idea what went wrong here, but that's pretty ugly.

File: site/src/Librecores/ProjectRepoBundle/Controller/OrganizationController.php [hunk 3]
```diff
@@ -393,15 +430,22 @@ public function denyAction($organizationName, $userName)
...
      */
-    public function removeAction($organizationName, $userName)
-    {
-        $o = $this->getDoctrine()
-            ->getRepository('LibrecoresProjectRepoBundle:Organization')
+    public function removeAction(
+        $organizationName,
+        $userName,
+        OrganizationRepository $repository,
+    UserManagerInterface $userManager
```
Comment (imphil) [inline site/src/Librecores/ProjectRepoBundle/Controller/OrganizationController.php]: indent?

File: site/src/Librecores/ProjectRepoBundle/Controller/OrganizationController.php [hunk 4]
```diff
@@ -377,8 +412,10 @@ public function denyAction($organizationName, $userName)
 
         // Update the organization membership
         $member = $this->getDoctrine()
-            ->getRepository('LibrecoresProjectRepoBundle:OrganizationMember')
-            ->findOneBy(['organization' => $o, 'user' => $user]);
+                       ->getRepository(
+                           'LibrecoresProjectRepoBundle:OrganizationMember'
+                       )
+                       ->findOneBy(['organization' => $o, 'user' => $user]);
```
Comment (imphil) [inline site/src/Librecores/ProjectRepoBundle/Controller/OrganizationController.php]: The original code was easy to read, the reformatted on is hard to read. Just leave the original one?

File: site/src/Librecores/ProjectRepoBundle/Controller/OrganizationController.php [hunk 5]
```diff
@@ -349,15 +379,21 @@ public function approveAction($organizationName, $userName)
...
      */
-    public function denyAction($organizationName, $userName)
-    {
-        $o = $this->getDoctrine()
-            ->getRepository('LibrecoresProjectRepoBundle:Organization')
+    public function denyAction(
+        $organizationName,
+        $userName,
+        OrganizationRepository $repository,
+    UserManagerInterface $userManager
```
Comment (imphil) [inline site/src/Librecores/ProjectRepoBundle/Controller/OrganizationController.php]: indent?

File: site/src/Librecores/ProjectRepoBundle/Controller/OrganizationController.php [hunk 6]
```diff
@@ -332,9 +362,9 @@ public function approveAction($organizationName, $userName)
         }
 
         // Update the organization membership
-        $member = $this->getDoctrine()
-            ->getRepository('LibrecoresProjectRepoBundle:OrganizationMember')
-            ->findOneBy(['organization' => $o, 'user' => $user]);
+        $member = $this->getDoctrine()->getRepository(
+            'LibrecoresProjectRepoBundle:OrganizationMember'
+        )->findOneBy(['organization' => $o, 'user' => $user]);
```
Comment (imphil) [inline site/src/Librecores/ProjectRepoBundle/Controller/OrganizationController.php]: That's harder to read than the original code.
