### PR TITLE
Resolve classification validation bug

### LINKED ISSUE #263: Classification validation sometimes fails
STR:
- Go to the settings page of any project
- Add the classification "Proven on::FPGA::Altera/Intel"
- Click on "Add classification"
- Click on "Update Project"

Result:
Error message " Invalid classifications - Proven on::FPGA::Altera/Intel "

Expected Result:
classification is added

@sandipbhuyan you mentioned this or a similar bug in the last call, but I didn't find an open issue.

### PR DESCRIPTION
**Pull request by sandipbhuyan**
Resolves #263

### CODE REVIEW

File: site/web/assets/js/classification.js [hunk 1]
```diff
@@ -21,24 +22,21 @@ var insertClassification = function (classificationDetails) {
...
+        var id = selected.data('id');
         for (var i = 0; i < classificationDetails.length; i++) {
           if (classificationDetails[i]['parentId'] === id) {
             if (increase === false) {
               var category = $('#category-' + count).clone().appendTo('.classification-system');
               count++;
               category.attr('id', 'category-' + count).empty().append('<option value="NULL">select a category</option>');
-              $('#category-' + count).append($('<option>').val(classificationDetails[i]['name']).html(classificationDetails[i]['name']));
+              $('#category-' + count).append($('<option>').val(classificationDetails[i]['name']).html(classificationDetails[i]['name'])
+                .attr('data-id',classificationDetails[i]['id']));
```
Comment (imphil) [inline site/web/assets/js/classification.js]: Please reduce the length of these lines to a sane ~ 80-100 characters, it's not even fitting the GitHub diff view, which makes review annoying.
And add a space after the ",", e.g. `.attr('data-id', classificationDetails[i]['id'])`

(This also applies to other places in this file, please fix accordingly.)

**Comment by imphil** [comment]
Thanks. Please combine the two commits and give a suitable commit message which includes the solved bug number, what the problem was, and how you solved it. You can force-push to the branch in this PR to update it.
